on:
  push:
    branches:
      - main

jobs:
  my-job:
    name: A job to say hello
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        id: hello
        uses: tobias-testing/barsoom@0.0.2
        with:
          name: Brown

      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"
